### ISSUE TITLE
 关于您存储库中涉及张家港农商问题的沟通

### ISSUE THREAD

**Issue by yeeton-bj** [palant/chrome-extension-manifests-dataset#10]
你好，
    受张家港农商银行委托，与您就github存储库问题进行沟通。经银行技术部门反馈，您在github上发布的以下链接中的内容涉及张家港农商关键字数据。银行表示并未授权给任何人上传该平台，且张家港农商银行在进行安全护网行动需要删除关键的银行信息。请处置此链接相关内容，谢谢您的合作！
https://github.com/palant/chrome-extension-manifests-dataset/blob/61dc2c37c2c4aeb0c97b7b88150ee5ca95366bed/manifests-2024-01-12/pfjphmlkocjhmnggdaomcdkkoaebaddn.json#L2
https://github.com/palant/chrome-extension-manifests-dataset/blob/61dc2c37c2c4aeb0c97b7b88150ee5ca95366bed/manifests-2023-11-29/pfjphmlkocjhmnggdaomcdkkoaebaddn.json#L2
![image](https://github.com/user-attachments/assets/71514c99-4919-41fa-ab12-4df79fb1628d)

**Comment by palant** [comment]
This is public information, identical to https://chromewebstore.google.com/detail/cfca-certenrollmentzrcban/pfjphmlkocjhmnggdaomcdkkoaebaddn. In particular, the domain zrcbank.com is not a secret, it’s literally the bank’s public domain name.

**Comment by yeeton-bj** [comment]
> 这是公开信息，与https://chromewebstore.google.com/detail/cfca-certenrollmentzrcban/pfjphmlkocjhmnggdaomcdkkoaebaddn相同。具体来说，zrcbank.com 这个域名并不是秘密，它实际上是银行的公共域名。

由于最近金融行业都在进行护网行动，目前严查全网银行关键域名，对于github上关键域名为重点监测对象，可否帮忙删除关键字样“zrcbank”，因为现在监测频率为一天一次，可能会频繁与您联系，为了不打扰到您，能否协助删除关键字即可。

**Comment by palant** [comment]
No, I am definitely not deleting information that has no security relevance whatsoever. I suggest that you start by contacting Google to delete your customer’s domain name from their index.
