### ISSUE TITLE
有关您在github上侵权江苏张家港农村商业银行股份有限公司问题沟通 

### ISSUE THREAD

**Issue by yeeton111** [palant/chrome-extension-manifests-dataset#6]
您好，
我们是为江苏张家港农村商业银行股份有限公司提供安全服务的厂商-北京亿盾互联科技有限公司。受张家港农村商业银行委托，跟您沟通有关您侵权张家港农村商业银行的问题。您在github上发布的以下链接中的内容涉及张家港农村商业银行内部银行信息及敏感信息，请您处理链接内容删除此库，否则张家港农村商业银行将进行追责，谢谢配合！
侵权内容链接：
https://github.com/palant/chrome-extension-manifests-dataset/blob/61dc2c37c2c4aeb0c97b7b88150ee5ca95366bed/manifests-2024-01-12/pfjphmlkocjhmnggdaomcdkkoaebaddn.json#L2
https://github.com/palant/chrome-extension-manifests-dataset/blob/61dc2c37c2c4aeb0c97b7b88150ee5ca95366bed/manifests-2023-11-29/pfjphmlkocjhmnggdaomcdkkoaebaddn.json#L2
侵权截图：
![图片1](https://github.com/palant/chrome-extension-manifests-dataset/assets/111103201/a804eb39-687c-4864-864c-4b47a073968f)
![图片2](https://github.com/palant/chrome-extension-manifests-dataset/assets/111103201/26af95e3-12cd-471d-a4da-4684fa78e919)

**Comment by palant** [comment]
This is only the public information listed on https://chromewebstore.google.com/detail/cfca-certenrollmentzrcban/pfjphmlkocjhmnggdaomcdkkoaebaddn, nothing confidential.

**Comment by yeeton111** [comment]
Because Jiangsu Zhangjiagang Rural Commercial Bank Co., Ltd. is currently carrying out network protection operations and needs to delete key bank information, and there are uncertain factors that may bring security risks to Jiangsu Zhangjiagang Rural Commercial Bank and its users. Please delete the relevant content as soon as possible. Thank you for your cooperation. !

**Comment by palant** [comment]
As I said, there is no private or sensitive information here. It’s a public browser extension, it can be found with a simple web search. And it’s essentially the same information as listed in Chrome Web Store.

**Comment by palant** [comment]
There is also more extensive information on that extension under https://chrome-stats.com/d/pfjphmlkocjhmnggdaomcdkkoaebaddn for example.
