### ISSUE TITLE
关于您在github上绍兴银行的问题沟通，请配合处理

### ISSUE THREAD

**Issue by yeeton111** [palant/chrome-extension-manifests-dataset#7]
您好，
我们是为绍兴银行股份有限公司提供安全服务的厂商-北京亿盾互联科技有限公司。受绍兴银行委托，跟您沟通有关您发布存储库里涉及绍兴银行的问题。您在github上发布的以下1个链接中的内容涉及绍兴银行信息，因绍兴银行现在进行护网行动需要删除银行关键信息并且具有不定因素可能给绍兴银行及其用户带来了安全风险，请帮忙删掉此信息。谢谢配合！

内容链接：    
https://github.com/metowolf/vCards/blob/2c23090a385bc759f7ae13f168293b0f273a3730/src/const/block.js#L4
侵权内容截图：
![微信截图_20240306110619](https://github.com/palant/chrome-extension-manifests-dataset/assets/111103201/bc6d9056-ec11-4a1f-bd2e-a91fcb692999)

**Comment by palant** [comment]
Once again, this is public information listed on https://chromewebstore.google.com/detail/cfca-certenrollmentsxccb/iapcgihppihpcegfmjobpeeongnnfodc. Same reasoning as in #6 applies.
