### ISSUE TITLE
侵权事宜

### ISSUE THREAD

**Issue by yeeton111** [palant/chrome-extension-manifests-dataset#8]
之前已经联系过您了，并说明这是由绍兴银行反馈处置的，因为现在绍兴进行护网行动需要删除银行关键信息并且具有不定因素可能给银行带来安全风险，所以联系您删除。相关资料我们是可以提供的。您删我留言也会有我们的其他工作人员联系您的。

**Comment by palant** [comment]
Yes. You did not explain however how the bank’s domain being mentioned somewhere is a security risk. Particularly when it is merely a copy of public extension information.

**Comment by yeeton111** [comment]
> 是的。然而，您没有解释某处提到的银行域名如何构成安全风险。特别是当它只是公共扩展信息的副本时。
因中国两会关系，银行方面需要进行全方面网络监测护网阶段，银行未授权您发布银行相关“URL”这对于银行来说是具有不定的安全因素，您可以尽量删除此银行相关信息或删除储存库，在此代表银行感谢您的配合。

**Comment by palant** [comment]
The first domain mentioned brings up 5,040 Google results, the second 35,300 results. Are these domains private information? :thinking:

**Comment by yeeton111** [comment]
我并没有说这些信息是私人的，您所提到的“第一个域会显示 5,040 个 Google 结果，第二个域会显示 35,300 个结果”这些结果里您如何得知是否未授权的那，您现在是所发布的内容涉及到绍兴银行内容或信息、关键字等是由银行反馈回来是需要删除的，您想要相关证明我们也是可以提供的，银行最低要求是删除关键字，您这边能否配合，我这边会如实反馈给银行。感谢您耐心回复。
