### ISSUE TITLE
Sorry，It comes to company privacy, please update the plug-in to version 1.3.0 and upload it again

### ISSUE THREAD

**Issue by MikuBlog** [palant/chrome-extension-manifests-dataset#9]
https://github.com/palant/chrome-extension-manifests-dataset/blob/61dc2c37c2c4aeb0c97b7b88150ee5ca95366bed/manifests-2024-01-12/lgceaaoefoccnafhogkggdahioflncof.json#L48

This involves our domain name, please update the plugin or delete the plugin to remove this sensitive information

**Comment by palant** [comment]
A new snapshot has been uploaded with the current manifest of the extension. Older versions of it have been removed.
